name: Extra Library Checks

on:
  - pull_request
  - push

env:
  ARDUINO_CI_SCRIPT_FOLDER: extras/ci-tools/arduino-ci-script

jobs:
  check-library-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install arduino-ci-script
        uses: per1234/install-arduino-ci-script-action@main
        with:
          installation-path: ${{ env.ARDUINO_CI_SCRIPT_FOLDER }}

      # See: https://github.com/per1234/arduino-ci-script#check_library_structure-basepath-depth
      - name: Check library structure
        run: |
          source "${ARDUINO_CI_SCRIPT_FOLDER}/arduino-ci-script.sh"
          check_library_structure "$GITHUB_WORKSPACE"

  check-library-properties:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install arduino-ci-script
        uses: per1234/install-arduino-ci-script-action@main
        with:
          installation-path: ${{ env.ARDUINO_CI_SCRIPT_FOLDER }}

      # See: https://github.com/per1234/arduino-ci-script#check_library_properties-searchpath-maximumsearchdepth
      - name: Check library.properties
        run: |
          source "${ARDUINO_CI_SCRIPT_FOLDER}/arduino-ci-script.sh"
          check_library_properties "$GITHUB_WORKSPACE"

  check-keywords-txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install arduino-ci-script
        uses: per1234/install-arduino-ci-script-action@main
        with:
          installation-path: ${{ env.ARDUINO_CI_SCRIPT_FOLDER }}

      # See: https://github.com/per1234/arduino-ci-script#check_keywords_txt-searchpath-maximumsearchdepth
      - name: Check keywords.txt
        run: |
          source "${ARDUINO_CI_SCRIPT_FOLDER}/arduino-ci-script.sh"
          check_keywords_txt "$GITHUB_WORKSPACE"

  check-library-manager-compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install arduino-ci-script
        uses: per1234/install-arduino-ci-script-action@main
        with:
          installation-path: ${{ env.ARDUINO_CI_SCRIPT_FOLDER }}

      # See: https://github.com/per1234/arduino-ci-script#check_library_manager_compliance-librarypath
      - name: Check Library Manager compliance
        run: |
          source "${ARDUINO_CI_SCRIPT_FOLDER}/arduino-ci-script.sh"
          check_library_manager_compliance "$GITHUB_WORKSPACE"
